packages:
  - apps/*
  - packages/*
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  protobufjs: true
  esbuild: true
  sharp: false
  unrs-resolver: false
  '@firebase/util': true
